In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Tensors

In [ ]:
scalar = torch.tensor(5)
print(f'Number of dimensions for scalar: {scalar.ndim}')
print(f'The size of scalar: {scalar.shape}')

Number of dimensions for scalar: 0
The size of scalar: torch.Size([])


In [ ]:
vector = torch.tensor([3, 7, 9, 1])
print(f'Number of dimensions for vector: {vector.ndim}')
print(f'The size of vector: {vector.shape}')

Number of dimensions for vector: 1
The size of vector: torch.Size([4])


In [ ]:
MATRIX = torch.tensor([
    [102, 4, 92, 3],
    [9, 4, 22, 33],
    [3, 8, 10, 143]
])
print(f'Number of dimensions for matrix: {MATRIX.ndim}')
print(f'The size of matrix: {MATRIX.shape}')

Number of dimensions for matrix: 2
The size of matrix: torch.Size([3, 4])


In [ ]:
TENSOR = torch.tensor([
    [
        [3, 6, 7, 10, 45],
        [1, 3, 5, 12, 41],
        [12, 40, 140, 402, 2]
    ],
    [
        [20, 23, 103, 34, 1],
        [12, 26, 0, 0, 32],
        [34, 21, 56, 23, 5]
    ]
])
print(f'Number of dimensions for tensor: {TENSOR.ndim}')
print(f'The size of tensor: {TENSOR.shape}')

Number of dimensions for tensor: 3
The size of tensor: torch.Size([2, 3, 5])


## Random Tensors

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.3102, 0.8457, 0.8214, 0.5714],
        [0.0474, 0.4861, 0.3023, 0.9762],
        [0.4564, 0.5543, 0.2806, 0.8883]])

## Tensors w/ Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of Tensors

In [ ]:
one_to_25_3 = torch.arange(start=1, end=25, step=3)
one_to_25_3

tensor([ 1,  4,  7, 10, 13, 16, 19, 22])

In [ ]:
torch.zeros_like(input=one_to_25_3)

tensor([0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [ ]:
my_tensor = torch.tensor(data=[3, 6, 9],
                         dtype=None,
                         device=None, # where the tensor lives (could be cpu, gpu, cuda, tpu, etc)
                         requires_grad=False) # whether we are keeping track of gradient
my_tensor

tensor([3, 6, 9])

In [ ]:
my_16_bit_tensor = my_tensor.type(dtype=torch.float16)
my_16_bit_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Tensor Attributes
The main tensor attributes to know are `.dtype`, `.shape`, and `.device`

## Tensor Operations

In [ ]:
# addition
tensor_a = torch.arange(1, 20, 2)
tensor_b = torch.arange(1, 11, 1)
print(f'tensor a: {tensor_a}')
print(f'tensor b: {tensor_b}')
print(f'adding tensor a and tensor b: {torch.add(tensor_a, tensor_b)}')

tensor a: tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor b: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
adding tensor a and tensor b: tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])


In [ ]:
# subtraction
print(f'tensor a: {tensor_a}')
print(f'tensor b: {tensor_b}')
print(f'subtracting tensor a and tensor b: {torch.subtract(tensor_a, tensor_b)}')

tensor a: tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor b: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
subtracting tensor a and tensor b: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# scalar multip.
print(f'tensor a: {tensor_a}')
print(f'tensor b: {tensor_b}')
print(f'subtracting tensor a and tensor b: {torch.multiply(tensor_a, tensor_b)}')

tensor a: tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor b: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
subtracting tensor a and tensor b: tensor([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190])


In [ ]:
# dot product
mat1 = torch.rand(size=(3,2))
mat2 = torch.rand(size=(2,3))
print(f'tensor a: {mat1}')
print(f'tensor b: {mat2}')
print(f'matrix multiplying tensor a and tensor b: {torch.matmul(mat1, mat2)}')

tensor a: tensor([[0.7144, 0.1995],
        [0.4107, 0.5123],
        [0.9097, 0.7384]])
tensor b: tensor([[0.1204, 0.7435, 0.3887],
        [0.1002, 0.9581, 0.8049]])
matrix multiplying tensor a and tensor b: tensor([[0.1060, 0.7223, 0.4383],
        [0.1008, 0.7962, 0.5720],
        [0.1835, 1.3839, 0.9480]])


## Transpose

In [ ]:
mat1 = torch.rand(size=(3,2))
mat2 = torch.rand(size=(3,2))
print(f'tensor a: {mat1}')
print(f'tensor b: {mat2}')
print(f'tranpose of b is: {mat2.T}')
print(f'matrix multiplying tensor a and tranpose tensor b: {torch.matmul(mat1, mat2.T)}')

tensor a: tensor([[0.0655, 0.3542],
        [0.1731, 0.7256],
        [0.3856, 0.2990]])
tensor b: tensor([[0.4872, 0.3017],
        [0.3233, 0.1569],
        [0.6459, 0.2387]])
tranpose of b is: tensor([[0.4872, 0.3233, 0.6459],
        [0.3017, 0.1569, 0.2387]])
matrix multiplying tensor a and tranpose tensor b: tensor([[0.1388, 0.0768, 0.1269],
        [0.3033, 0.1698, 0.2849],
        [0.2781, 0.1716, 0.3204]])


## Aggregation (min, max, mean, sum, etc.)

In [ ]:
x = torch.arange(0, 150, 13)
x

tensor([  0,  13,  26,  39,  52,  65,  78,  91, 104, 117, 130, 143])

In [ ]:
# min
torch.min(x)

tensor(0)

In [ ]:
# max
torch.max(x)

tensor(143)

In [ ]:
# mean --> requires it to be float or complex dtype
torch.mean(x.type(torch.float32))

tensor(71.5000)

In [ ]:
# sum
torch.sum(x)

tensor(858)

## Positional min/max

In [ ]:
print(f'The max value of x is at index {x.argmax()}')
print(f'The min value of x is at index {x.argmin()}')


The max value of x is at index 11
The min value of x is at index 0


## Manipulating sizes of tensors

In [ ]:
tensor = torch.rand(size=(3,2,4))
tensor

tensor([[[0.8891, 0.6313, 0.3607, 0.9815],
         [0.9026, 0.1069, 0.2256, 0.0889]],

        [[0.3550, 0.5190, 0.2431, 0.1199],
         [0.9147, 0.8241, 0.6365, 0.6135]],

        [[0.4296, 0.1176, 0.9161, 0.1689],
         [0.6186, 0.6926, 0.6698, 0.2778]]])

In [ ]:
# reshaping --> changes tensor to desired shape if possible
tensor.reshape(shape=(6,2,2))

tensor([[[0.8891, 0.6313],
         [0.3607, 0.9815]],

        [[0.9026, 0.1069],
         [0.2256, 0.0889]],

        [[0.3550, 0.5190],
         [0.2431, 0.1199]],

        [[0.9147, 0.8241],
         [0.6365, 0.6135]],

        [[0.4296, 0.1176],
         [0.9161, 0.1689]],

        [[0.6186, 0.6926],
         [0.6698, 0.2778]]])

In [ ]:
# view --> view tensor with the desired size while it shares memory with original tensor
tensor.view(size=(6,2,2))

tensor([[[0.8891, 0.6313],
         [0.3607, 0.9815]],

        [[0.9026, 0.1069],
         [0.2256, 0.0889]],

        [[0.3550, 0.5190],
         [0.2431, 0.1199]],

        [[0.9147, 0.8241],
         [0.6365, 0.6135]],

        [[0.4296, 0.1176],
         [0.9161, 0.1689]],

        [[0.6186, 0.6926],
         [0.6698, 0.2778]]])

In [ ]:
# stacking --> add tensors along different axes
torch.stack(tensors=(tensor, tensor), dim=0) # stacking on dim 0

tensor([[[[0.8891, 0.6313, 0.3607, 0.9815],
          [0.9026, 0.1069, 0.2256, 0.0889]],

         [[0.3550, 0.5190, 0.2431, 0.1199],
          [0.9147, 0.8241, 0.6365, 0.6135]],

         [[0.4296, 0.1176, 0.9161, 0.1689],
          [0.6186, 0.6926, 0.6698, 0.2778]]],


        [[[0.8891, 0.6313, 0.3607, 0.9815],
          [0.9026, 0.1069, 0.2256, 0.0889]],

         [[0.3550, 0.5190, 0.2431, 0.1199],
          [0.9147, 0.8241, 0.6365, 0.6135]],

         [[0.4296, 0.1176, 0.9161, 0.1689],
          [0.6186, 0.6926, 0.6698, 0.2778]]]])

In [ ]:
# stacking on dim 1
torch.stack(tensors=(tensor, tensor), dim=1)

tensor([[[[0.8891, 0.6313, 0.3607, 0.9815],
          [0.9026, 0.1069, 0.2256, 0.0889]],

         [[0.8891, 0.6313, 0.3607, 0.9815],
          [0.9026, 0.1069, 0.2256, 0.0889]]],


        [[[0.3550, 0.5190, 0.2431, 0.1199],
          [0.9147, 0.8241, 0.6365, 0.6135]],

         [[0.3550, 0.5190, 0.2431, 0.1199],
          [0.9147, 0.8241, 0.6365, 0.6135]]],


        [[[0.4296, 0.1176, 0.9161, 0.1689],
          [0.6186, 0.6926, 0.6698, 0.2778]],

         [[0.4296, 0.1176, 0.9161, 0.1689],
          [0.6186, 0.6926, 0.6698, 0.2778]]]])

In [ ]:
# stacking on dim 2
torch.stack(
    tensors=(tensor, tensor),
    dim=2
)

tensor([[[[0.8891, 0.6313, 0.3607, 0.9815],
          [0.8891, 0.6313, 0.3607, 0.9815]],

         [[0.9026, 0.1069, 0.2256, 0.0889],
          [0.9026, 0.1069, 0.2256, 0.0889]]],


        [[[0.3550, 0.5190, 0.2431, 0.1199],
          [0.3550, 0.5190, 0.2431, 0.1199]],

         [[0.9147, 0.8241, 0.6365, 0.6135],
          [0.9147, 0.8241, 0.6365, 0.6135]]],


        [[[0.4296, 0.1176, 0.9161, 0.1689],
          [0.4296, 0.1176, 0.9161, 0.1689]],

         [[0.6186, 0.6926, 0.6698, 0.2778],
          [0.6186, 0.6926, 0.6698, 0.2778]]]])

In [ ]:
# squeeze --> remove dimensions with size 1
tensor = torch.tensor(
    data=[[[2,4,6,8], [3, 6, 9, 12]]]
)
print(f'original shape: {tensor.shape}')
squeezed_tensor = torch.squeeze(input=tensor)
print(f'squeezed shape: {squeezed_tensor.shape}')
squeezed_tensor

original shape: torch.Size([1, 2, 4])
squeezed shape: torch.Size([2, 4])


tensor([[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]])

In [ ]:
# unsqueeze --> add 1 dimension
add_dim_0 = torch.unsqueeze(input=tensor, dim=0)
print(f'tensor when adding 1 to dim 0 : \n{add_dim_0}')
print(f'shape: {add_dim_0.shape}')
add_dim_1 = torch.unsqueeze(input=tensor, dim=1)
print(f'tensor when adding 1 to dim 1: \n{add_dim_1}')
print(f'shape: {add_dim_1.shape}')
add_dim_2 = torch.unsqueeze(input=tensor, dim=2)
print(f'tensor when adding 1 to dim 2: \n{add_dim_2}')
print(f'shape: {add_dim_2.shape}')
add_dim_3 = torch.unsqueeze(input=tensor, dim=3)
print(f'tensor when adding 1 to dim 3: \n {add_dim_3}')
print(f'shape: {add_dim_3.shape}')





tensor when adding 1 to dim 0 : 
tensor([[[[ 2,  4,  6,  8],
          [ 3,  6,  9, 12]]]])
shape: torch.Size([1, 1, 2, 4])
tensor when adding 1 to dim 1: 
tensor([[[[ 2,  4,  6,  8],
          [ 3,  6,  9, 12]]]])
shape: torch.Size([1, 1, 2, 4])
tensor when adding 1 to dim 2: 
tensor([[[[ 2,  4,  6,  8]],

         [[ 3,  6,  9, 12]]]])
shape: torch.Size([1, 2, 1, 4])
tensor when adding 1 to dim 3: 
 tensor([[[[ 2],
          [ 4],
          [ 6],
          [ 8]],

         [[ 3],
          [ 6],
          [ 9],
          [12]]]])
shape: torch.Size([1, 2, 4, 1])


In [ ]:
# permute --> swap dimensions to desired ordering
tensor = torch.rand(size=(5,2,4))
permuted_tensor = torch.permute(tensor, (2, 1, 0))
permuted_tensor.shape

torch.Size([4, 2, 5])

## Indexing
Works same as NumPy

In [ ]:
x = torch.arange(1,10).reshape((1,3,3))
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

## Torch & NumPy compatability

In [ ]:
arr = np.arange(1,9)
tensor = torch.from_numpy(arr)
arr, arr.dtype, tensor, tensor.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 dtype('int64'),
 tensor([1, 2, 3, 4, 5, 6, 7, 8]),
 torch.int64)

In [ ]:
tensor = torch.ones(3)
nparr = tensor.numpy()
nparr

array([1., 1., 1.], dtype=float32)

## Reproducibility

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand((2,3))
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand((2,3))
print(random_tensor_A == random_tensor_B)

tensor([[True, True, True],
        [True, True, True]])


### GPU Info

In [ ]:
!nvidia-smi

Sat Jun 15 23:07:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# device agnostic code!
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving gpu tensor back to numpy
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])